# Logistic regression (week 3)

```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}
library(tidyverse)
library(knitr)
library(caret)
library(dplyr)
library(ggplot2)
library(GGally)
require(gridExtra)
require(docxtools)
library(ggcorrplot)
```

```{r message=FALSE, warning=FALSE}
# load data set
alc <- read_csv("./data/alc.csv")

# variables in the data set
print(colnames(alc))
```

```{r cm, message=FALSE, warning=FALSE, fig.cap="Correlation matrix for student alcohol consumption data set.\\label{fig:cm}", fig.align="center", fig.width=12, fig.height=12}
model.matrix(~0+., data=alc) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag=FALSE, type="lower", lab=TRUE, lab_size=2)
```
```{r bp, message=FALSE, warning=FALSE, fig.cap=".\\label{fig:bp}", fig.align="center", fig.width=15, fig.height=8}
h1 <- ggplot(alc, aes(x = goout, fill = high_use)) + 
   geom_histogram(alpha = 0.7) + ylab("Density") + 
  ggtitle("Go out by alcohol consumption") + 
  scale_fill_brewer(palette="Set2")
h2 <- ggplot(alc, aes(x = absences, fill = high_use)) + 
  geom_density(alpha = 0.7) + ylab("Density") + 
  ggtitle("Absences by alcohol consumption") + 
  scale_fill_brewer(palette="Set2")
h3 <- ggplot(alc, aes(x = G3, fill = high_use)) + 
  geom_density(alpha = 0.7) + ylab("Density") + 
  ggtitle("Final exam score by alcohol consumption") + 
  scale_fill_brewer(palette="Set2")
  
b1 <- ggplot(alc, aes(x = high_use, y = goout, col = sex)) + geom_boxplot() + 
  ylab("Go out") + ggtitle("Go out by alcohol consumption and sex")
b2 <- ggplot(alc, aes(x = high_use, y = absences, col = sex)) + geom_boxplot() + 
  ylab("Absences") + ggtitle("Absences by alcohol consumption and sex")
b3 <- ggplot(alc, aes(x = high_use, y = G3, col = sex)) + geom_boxplot() + 
  ylab("G3") + ggtitle("Final exam score by alcohol consumption and sex")

grid.arrange(h1, h2, h3, b1, b2, b3, ncol=3, nrow=2)
```

```{r}
model <- glm(high_use ~ sex + goout + absences + G3, data = alc, 
             family = "binomial")
summary(model)

model <- glm(high_use ~ sex + goout + absences, data = alc, 
             family = "binomial")
summary(model)

alc_model <- data.frame(high_use=alc$high_use,
                        high_use_prob=predict(model, type = "response"))
alc_model <- mutate(alc_model, high_use_predict=high_use_prob>0.5)

ggplot(alc_model, aes(x = high_use_prob, 
                     y = high_use, col = high_use_predict)) + 
  geom_point() + scale_color_brewer(palette="Set2")

table(high_use = alc_model$high_use, 
      prediction = alc_model$high_use_predict) %>% prop.table %>% addmargins

train_err <- mean(abs(alc_model$high_use - alc_model$high_use_prob) > 0.5)
train_err
```

